// @vitest-environment happy-dom
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { PetWidget } from '../src/pet/pet-widget';
import { DEFAULT_SETTINGS } from '../src/shared/types';

let settings = { ...DEFAULT_SETTINGS };
let pet: PetWidget;
const get = vi.fn(async () => ({ 'fwa:settings': settings }));
const set = vi.fn(async (items: Record<string, unknown>) => { settings = items['fwa:settings'] as typeof settings; });

function button(): HTMLButtonElement {
  return document.getElementById('fwa-pet-host')!.shadowRoot!.querySelector('button')!;
}
function pointer(type: string, x: number, y: number): void {
  button().dispatchEvent(new PointerEvent(type, { button: 0, pointerId: 1, clientX: x, clientY: y, bubbles: true }));
}

beforeEach(() => {
  settings = { ...DEFAULT_SETTINGS };
  get.mockReset().mockImplementation(async () => ({ 'fwa:settings': settings }));
  set.mockClear();
  vi.stubGlobal('chrome', { runtime: { getURL: (path: string) => `https://extension.test/${path}` }, storage: { local: { get, set } } });
  vi.stubGlobal('fetch', vi.fn(async () => new Response('', { status: 404 })));
  vi.spyOn(console, 'debug').mockImplementation(() => {});
  vi.spyOn(HTMLElement.prototype, 'getBoundingClientRect').mockImplementation(function (this: HTMLElement) {
    return new DOMRect(parseFloat(this.style.left) || 600, parseFloat(this.style.top) || 500, 72, 72);
  });
  Object.defineProperties(HTMLElement.prototype, {
    setPointerCapture: { configurable: true, value: vi.fn() },
    hasPointerCapture: { configurable: true, value: () => false },
    releasePointerCapture: { configurable: true, value: vi.fn() },
  });
  pet = new PetWidget();
});

afterEach(() => {
  pet.detach();
  vi.useRealTimers();
  vi.unstubAllGlobals();
  vi.restoreAllMocks();
});

describe('Pet customer shortcut', () => {
  it('rebinds a live Pet without resetting its image or requesting it again', () => {
    const first = vi.fn();
    const second = vi.fn();
    pet.attach(first);
    const original = button();
    const sprite = original.querySelector<HTMLElement>('.fwa-pet-sprite')!;
    sprite.style.backgroundImage = 'url("https://extension.test/loaded.png")';
    sprite.replaceChildren();
    pet.attach(second);
    expect(button()).toBe(original);
    expect(button().querySelector('.fwa-pet-sprite')).toBe(sprite);
    expect(sprite.style.backgroundImage).toContain('loaded.png');
    expect(fetch).toHaveBeenCalledOnce();
    button().click();
    expect(first).not.toHaveBeenCalled();
    expect(second).toHaveBeenCalledOnce();
  });

  it('keeps a full pointer gesture out of Wiki document handlers', () => {
    const nativeHandler = vi.fn();
    const open = vi.fn();
    const events = ['pointerdown', 'mousedown', 'pointerup', 'click'];
    events.forEach((type) => document.addEventListener(type, nativeHandler));
    try {
      pet.attach(open);
      for (const type of events) {
        button().dispatchEvent(new PointerEvent(type, { button: 0, pointerId: 1, bubbles: true, composed: true }));
      }
      expect(open).toHaveBeenCalledOnce();
      expect(nativeHandler).not.toHaveBeenCalled();
    } finally {
      events.forEach((type) => document.removeEventListener(type, nativeHandler));
    }
  });

  it('keeps a working accessible sprite shortcut when its image cannot load', async () => {
    const open = vi.fn();
    pet.attach(open);
    expect(button().textContent).not.toContain('🦀');
    expect(button().querySelector('.fwa-pet-fallback')).toBeNull();
    await vi.waitFor(() => expect(button().querySelector('.fwa-pet-fallback')?.textContent).toBe('W'));
    expect(button().getAttribute('aria-haspopup')).toBe('dialog');
    expect(button().querySelector('.fwa-pet-sprite')).not.toBeNull();
    expect(button().classList.contains('fwa-workspace-launcher')).toBe(false);
    button().click();
    expect(open).toHaveBeenCalledOnce();
    pet.setExpanded(true);
    expect(button().getAttribute('aria-expanded')).toBe('true');
    pet.setVisible(false);
    expect(button().hidden).toBe(true);
    expect(pet.getBounds()).toBeNull();
    pet.setVisible(true);
    expect(pet.getBounds()).not.toBeNull();
  });

  it('saves dragged positions and suppresses only the click generated by that drag', async () => {
    const open = vi.fn();
    pet.attach(open);
    await Promise.resolve();
    pointer('pointerdown', 600, 500);
    pointer('pointermove', 540, 460);
    pointer('pointerup', 540, 460);
    button().click();
    expect(open).not.toHaveBeenCalled();
    await vi.waitFor(() => expect(settings.petPosition?.xRatio).toBe(540 / window.innerWidth));
    expect(settings.petPosition?.yRatio).toBe(460 / window.innerHeight);
    pointer('pointerdown', 540, 460);
    pointer('pointerup', 540, 460);
    button().click();
    expect(open).toHaveBeenCalledOnce();
  });

  it('does not overwrite a user drag when saved-position loading finishes late', async () => {
    let resolveRead!: (value: { 'fwa:settings': typeof settings }) => void;
    get.mockImplementationOnce(() => new Promise((resolve) => { resolveRead = resolve; }));
    pet.attach(() => {});
    pointer('pointerdown', 600, 500);
    pointer('pointermove', 520, 450);
    pointer('pointerup', 520, 450);
    resolveRead({ 'fwa:settings': { ...settings, petPosition: { xRatio: 0.1, yRatio: 0.1 } } });
    await Promise.resolve();
    await Promise.resolve();
    expect(button().style.left).toBe('520px');
    expect(button().style.top).toBe('450px');
  });

  it('brings a hidden Pet back inside the viewport after the window shrinks', () => {
    pet.attach(() => {});
    pointer('pointerdown', 600, 500);
    pointer('pointermove', 700, 550);
    pointer('pointerup', 700, 550);
    pet.setVisible(false);
    vi.spyOn(window, 'innerWidth', 'get').mockReturnValue(360);
    vi.spyOn(window, 'innerHeight', 'get').mockReturnValue(640);
    window.dispatchEvent(new Event('resize'));
    pet.setVisible(true);
    expect(parseFloat(button().style.left)).toBeLessThanOrEqual(280);
    expect(parseFloat(button().style.top)).toBeLessThanOrEqual(560);
  });

  it('aborts in-flight image loading and removes its listeners on detach', () => {
    let signal: AbortSignal | null | undefined;
    vi.stubGlobal('fetch', vi.fn((_url: string, init: RequestInit) => {
      signal = init.signal;
      return new Promise(() => {});
    }));
    pet.attach(() => {});
    const original = button();
    pet.detach();
    expect(signal?.aborted).toBe(true);
    expect(original.isConnected).toBe(false);
    expect(document.getElementById('fwa-pet-host')).toBeNull();
    window.dispatchEvent(new Event('resize'));
    expect(pet.getBounds()).toBeNull();
  });
});
